### ISSUE TITLE
Failed to get Scalar Charts

### ISSUE THREAD

**Issue by LMerCy** [allegroai/trains#197] opened 2020-08-31 01:39 UTC
sometimes i got the error in web:Failed to get Scalar Charts
And i check the server log，it show the error:

> [ERROR] [trains.service_repo] Returned 500 for events.add_batch in 4ms, msg=General data error (TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [2041734978/1.9gb], which is larger than the limit of [2006987571/1.8gb], real usage: [2041711888/1.9gb], new bytes reserved: [23090/22.5kb], usages [request=0/0b, fielddata=3460/3.3kb, in_flight_requests=23090/22.5kb, accounting=259135/253kb]'))

version:0.16.0

how can i solve the problem?

**Comment by bmartinn** [comment] 2020-09-01 14:19
Hi @LMerCy 
I think this is a duplicate of #198 , could you verify ?

**Comment by LMerCy** [comment] 2020-09-03 07:41
@bmartinn 
Yes, after solve #198, this didn't happen again.

**Comment by bmartinn** [comment] 2020-09-04 21:04
Great to hear! closing this issue :)
BTW: we will be adding a configuration (in `trains.conf`) for limiting the number of digits reported by plots, so it is easier to control from outside the code :)

**Closed by bmartinn** 2020-09-04 21:04 UTC
